version: '3.1'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: john
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
